
@echo off
title LaTex Cleaner
del /a /f /q /s  "*.aux"
del /a /f /q /s  "*.aux"
del /a /f /q /s  "*.bak"
del /a /f /q /s  "*.bbl"
del /a /f /q /s  "*.bcf"
del /a /f /q /s  "*.blg"
del /a /f /q /s  "*.dvi"
del /a /f /q /s  "*.fdb_latexmk"
del /a /f /q /s  "*.fls"
del /a /f /q /s  "*.glg"
del /a /f /q /s  "*.glo"
del /a /f /q /s  "*.gls"
del /a /f /q /s  "*.hd"
del /a /f /q /s  "*.idx"
del /a /f /q /s  "*.ilg"
del /a /f /q /s  "*.ind"
del /a /f /q /s  "*.ist"
del /a /f /q /s  "*.lof"
del /a /f /q /s  "*.log"
del /a /f /q /s  "*.lot"
del /a /f /q /s  "*.out"
del /a /f /q /s  "*.run.xml"
del /a /f /q /s  "*.sav"
del /a /f /q /s  "*.synctex.gz"
del /a /f /q /s  "*.synctex\(busy\)"
del /a /f /q /s  "*.thm"
del /a /f /q /s  "*.toc"
del /a /f /q /s  "*.xdv"
